config/routes.rb
Gallery::Application.routes.draw do
  resources :paintings
  root to: 'paintings#index'
end

app/models/painting.rb
require 'plugins/filename_sanitizer'

class Painting < ActiveRecord::Base

  # Sanitizing filename should be done at js level, not here... help? Otherwise
  # Amazon adds some characters of their own to the filename in S3 if
  # they contain some weird characters. Eg: 'hello%20world' => 'hello%2520world'
  # This will fail the blitline_job method as it can't find the original image.
  include FilenameSanitizer

  attr_accessible :img_ori, :name

  before_save :run_blitline_job

  private

    def run_blitline_job
      filename = File.basename(img_ori, '.*')
      self.name ||= sanitize_filename(filename).titleize # set default name based on filename

      filename_with_ext = sanitize_filename(File.basename(img_ori))
      key = "uploads/large/#{SecureRandom.hex}/#{filename_with_ext}"
      key2 = "uploads/thumb/#{SecureRandom.hex}/#{filename_with_ext}"

      bucket = ENV["AWS_S3_BUCKET"]

      images = blitline_job(img_ori, bucket, key, key2)
      self.img_large = images['results'][0]['images'][0]['s3_url'] # extracts s3_url from blitline's ruby hashes
      self.img_thumb = images['results'][0]['images'][1]['s3_url']
    end

    def blitline_job(original_image, bucket, key, key2)
      blitline_service = Blitline.new
      blitline_service.add_job_via_hash({ # New add job method in Blitline gem 2.0.1. Messy.
        "application_id" => ENV['BLITLINE_APPLICATION_ID'],
        "src" => original_image,
        "functions" => [
          {
            "name"   => "resize_to_fit", # large version
            "params" => { "width"=>550,
                          "only_shrink_larger"=>true }, # don't upsize image if width smaller than 550px

            "functions" => [{
                "name"   => "pad",
                "params" => { "size"=>25, "color"=>"#ffffff", "gravity"=>"SouthGravity" },

                "functions" => [{
                    "name"   => "annotate",
                    "params" => { "x"=>5, "y"=>5, "point_size"=>"14",
                                  "text"=>"Find us at example.com",
                                  "color"=>"#8a8a8a", "gravity"=>"SouthEastGravity" },
                    "save"   => {
                        "image_identifier" => "MY_CLIENT_ID", # Not sure what this is for
                        "s3_destination"   => { "key" => key, "bucket" => bucket } # push to your S3 bucket
                    }
                }]
            }]
          },
          {
              "name"   => "resize_to_fill", # thumbnail version
              "params" => { "width"=>144, "height"=>216 },
              "save"   => {
                  "image_identifier" => "MY_CLIENT_ID",
                  "s3_destination"   => { "key" => key2, "bucket" => bucket }
              }
          }
        ]
      })
      return blitline_service.post_jobs
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def index
    @paintings = Painting.all
  end

  def show
    @painting = Painting.find(params[:id])
  end

  def new
    @painting = Painting.new
  end

  def create
    @painting = Painting.create(params[:painting])
  end

  def edit
    @painting = Painting.find(params[:id])
  end

  def update
    @painting = Painting.find(params[:id])
    if @painting.update_attributes(params[:painting])
      redirect_to paintings_url, notice: "Painting was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @painting = Painting.find(params[:id])
    @painting.destroy
    redirect_to paintings_url, notice: "Painting was successfully destroyed."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/helpers/upload_helper.rb
module UploadHelper
  def s3_uploader_form(options = {}, &block)
    uploader = S3Uploader.new(options)
    form_tag(uploader.url, uploader.form_options) do
      uploader.fields.map do |name, value|
        hidden_field_tag(name, value)
      end.join.html_safe + capture(&block)
    end
  end

  class S3Uploader
    def initialize(options)
      @options = options.reverse_merge(
        id: "fileupload",
        aws_access_key_id:      ENV["AWS_ACCESS_KEY_ID"],
        aws_secret_access_key:  ENV["AWS_SECRET_ACCESS_KEY"],
        bucket:                 ENV["AWS_S3_BUCKET"],
        acl: "public-read",
        expiration: 10.hours.from_now,
        max_file_size: 500.megabytes,
        as: "file"
      )
    end

    def form_options
      {
        id: @options[:id],
        method: "post",
        authenticity_token: false,
        multipart: true,
        data: {
          post: @options[:post],
          as: @options[:as]
        }
      }
    end

    def fields
      {
        :key => key,
        :acl => @options[:acl],
        :policy => policy,
        :signature => signature,
        "AWSAccessKeyId" => @options[:aws_access_key_id]
      }
    end

    def key
      @key ||= "uploads/originals/#{SecureRandom.hex}/${filename}"
    end

    def url
      "https://#{@options[:bucket]}.s3.amazonaws.com/"
    end

    def policy
      Base64.encode64(policy_data.to_json).gsub("\n", "")
    end

    def policy_data
      {
        expiration: @options[:expiration],
        conditions: [
          ["starts-with", "$utf8", ""],
          ["starts-with", "$key", ""],
          ["content-length-range", 0, @options[:max_file_size]],
          {bucket: @options[:bucket]},
          {acl: @options[:acl]}
        ]
      }
    end

    def signature
      Base64.encode64(
        OpenSSL::HMAC.digest(
          OpenSSL::Digest::Digest.new('sha1'),
          @options[:aws_secret_access_key], policy
        )
      ).gsub("\n", "")
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Painting Gallery</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/paintings/_form.html.erb
<%= form_for @painting do |f| %>
  <% if @painting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@painting.errors.count, "error") %> prohibited this painting from being saved:</h2>
      <ul>
      <% @painting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <p>
    <%= f.file_field :image %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paintings/_painting.html.erb
<div class="painting">
  <div class="frame">
    <%= link_to image_tag(painting.img_thumb), painting if painting.img_thumb %>
  </div>
  <div class="name"><%= painting.name %></div>
  <div class="actions">
    <%= link_to "edit", edit_painting_path(painting) %> |
    <%= link_to "remove", painting, :confirm => 'Are you sure?', :method => :delete %>
  </div>
</div>

app/views/paintings/create.js.erb
<% if @painting.new_record? %>
  alert("Failed to upload painting: <%= j @painting.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("#paintings").append("<%= j render(@painting) %>");
<% end %>

app/views/paintings/edit.html.erb
<h1>Editing Painting</h1>

<%= render 'form' %>

app/views/paintings/index.html.erb
<h1>Painting Gallery</h1>

<div id="paintings">
  <%= render @paintings %>
</div>
<div class="clear"></div>

<%= s3_uploader_form post: paintings_url, as: "painting[img_ori]" do %>
  <%= file_field_tag :file, multiple: true %>
<% end %>

<script id="template-upload" type="text/x-tmpl">
<div class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>

app/views/paintings/new.html.erb
<h1>Add a Painting</h1>

<%= render 'form' %>

app/views/paintings/show.html.erb
<h1><%= @painting.name %></h1>

<h3>Original image:</h3>
<%= image_tag @painting.img_ori %>

<h3>Large version:</h3>
<%= image_tag @painting.img_large %>

<h3>Thumbnail version:</h3>
<%= image_tag @painting.img_thumb %>

<p>
  <%= link_to "Edit", edit_painting_path(@painting) %> |
  <%= link_to "Destroy", @painting, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "Back to Paintings", paintings_path %>
</p>